### ISSUE TITLE
plot not found

### ISSUE THREAD

**Issue by Diakon8CZ** [mogua-network/mogua-blockchain#22]
**Describe the bug**

mogua app stoped adding new plots, which I´m making in mad max.
than I removed all my plot directorys and add them again, but it didn´t sort the problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome
 - 
![mogua bug](https://user-images.githubusercontent.com/93080253/138592919-5a680839-7cdc-4539-a43b-f8509b9c8f7d.png)

**Comment by Hoochie63** [comment]
Hey!
Close any programs that mine CHIA, for example, hpool. First, all the forks are launched, and only then the ChIA mining is launched.
